# Generated by Django 4.2.16 on 2024-11-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='doctor_profile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='doctor_profile'),
        ),
    ]
