# Generated by Django 4.2.16 on 2024-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
