# Generated by Django 4.2.16 on 2024-11-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_billing_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
