# Generated by Django 4.2.16 on 2024-11-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_doctor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_approved',
        ),
    ]
